### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [stoyan-shopov/troll#1]
looks like a very cool project! but your project description is now empty with "No description, website, or topics provided."?

keep it up, cheers!

**Comment by stoyan-shopov** [comment]
Thanks!

I have put a 'readme' file with a short description of the project, but I have not updated it for a couple of months. I am trying to push the project forward when I have the time, but it is difficult to tell what will turn out of this project.
I already have the basic stuff working (connecting to a target, flashing, breakpoints, single stepping, resetting, resuming and halting the target, displaying of backtraces, variables and source code context), but there is much, much, much more work to be done for the project to be generally usable. I am currently actively working on the project, with the last commit submitted four days ago.

I added a short description of the project.

By the way, I have been using the *Capstone* disassembler in the project for a few weeks, and it works great! Great job!

**Comment by aquynh** [comment]
great, linked to your project from our website now: http://www.capstone-engine.org/showcase.html.

keep it up, cheers.
